# title: Pages
# structure:
#   root: true
# route: "{parent_uri}/{slug}"
# propagate: true
title: Pages
structure:
  root: true
route: "{parent_uri}/{slug}"
propagate: true
blueprint:
  sections:
    main:
      display: Main
      fields:
        - handle: title
          field:
            type: text
            display: Title
        - handle: content
          field:
            type: markdown
            display: Content
        - handle: images
          field:
            type: assets
            display: Images
            container: assets
            max_files: 1
